# .github/workflows/update-readme.yml
name: Refresh Profile README

on:
  schedule:
    - cron: "0 8 * * *"   # every day at 08:00 UTC

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README
        run: |
          # e.g. insert a timestamp or fetch a new quote
          now=$(date -u +"%Y-%m-%d %H:%M UTC")
          sed -i "s/Last updated:.*/Last updated: $now/" README.md
- name: Commit & Push
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add README.md
    if ! git diff --cached --quiet; then
      git commit -m "📝 Update timestamp"
      git push
    else
      echo "No changes to commit"
    fi

